CUDA_VISIBLE_DEVICES=$2 OMP_NUM_THREADS=4 python3 main_il.py \
--random_seed=$1 \
--experiment_name=mill_word \
--task_id=False \
--lr=0.0005 \
--loss_type=reparam_loss \
--lambda_support=0.0 \
--lambda_query=0.1 \
--lambda_embedding=0.0000001 \
--datasetdir='../../datasets' --logdir='./log_1' \
--eval=False \
--eval_trainenv=False \
--no_mujoco=False \
--embedding_type=both_embedding  \
--sentence_type=both \
--sentence=word \
