CUDA_VISIBLE_DEVICES=-1 OMP_NUM_THREADS=1 python3 main_il_test.py \
--random_seed=$1 \
--experiment_name=mill_random_instruction_$1 \
--task_id=False \
--lr=0.0005 --loss_type=reparam_loss \
--lambda_support=0.0 --lambda_query=0.1 \
--lambda_embedding=0.0000001 \
--datasetdir='../../datasets' --logdir='./log_eval_test' \
--eval=True \
--embedding_type=both_embedding \
--sentence_type=both \
--sentence=15types \
--eval_trainenv=True --no_mujoco=False \
--eval_only=True --load=True --checkpoint_dir="./log_1" --checkpoint_iter=-1 \
